variable "location" {}
variable "vnet_address_space" {}
variable "subnet_name" {}
variable "vnet_name" {}
variable "dns_zone_name" {}
variable "dns_prefix" {}
variable "appgw_subnet_cidr" {}
variable "resource_group_name" {}
variable "subnet_address_prefix" {}
variable "aks_cluster_name" {}
variable "aks_node_pool_name" {}
variable "aks_node_count" {}
variable "aks_vm_size" {}
variable "aks_max_pods" {}
variable "aks_min_count" {}
variable "aks_max_count" {}
variable "aks_kubernetes_version" {}
variable "domain_name" {}
variable "tls_enabled" {}
variable "ssl_certificate_password" {}
